# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/seagate_2tb_hdd" = 
    { device = "/dev/disk/by-label/seagate_2tb_hdd";
      fsType = "ext4";
    };

  fileSystems."/samsung_1tb" = 
    { device = "/dev/disk/by-label/samsung_1tb";
      fsType = "ext4";
    };

  fileSystems."/crucial_1tb_1" = 
    { device = "/dev/disk/by-label/crucial_1tb_1";
      fsType = "ext4";
    };

  fileSystems."/crucial_1tb_2" = 
    { device = "/dev/disk/by-label/crucial_1tb_2";
      fsType = "ext4";
    };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f182f24e-2c5b-423e-9d4d-c23897c122e1";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E792-49A9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5ad97bab-2f6f-49bc-9b46-e0133468b4d5"; }
    ];

  boot.resumeDevice = "/dev/disk/by-uuid/5ad97bab-2f6f-49bc-9b46-e0133468b4d5";

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp10s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp9s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
